// ==========================DEV VARIABLES ====================================================================================
export const ROOT_URL = "";//'http://frontend-dev1.bwaserver.com';
export const ANALYTICS_URL = 'http://reporting-dev.bwaserver.com';

export const PUBID_URL = 'http://reporting-dev.bwaserver.com/api/managed_reports/services/legacy_placements/';
export const PUB_REPORT_URL = 'http://reporting-dev.bwaserver.com/api/managed_reports/publisher_report/';
export const PUB_ALL_PID = 'http://reporting-dev.bwaserver.com/api/managed_reports/services/legacy_placements_all/';

export const PUB_CSV_URL = 'http://reporting-dev.bwaserver.com/api/managed_reports/csv/?fn=';
export const CSV_URL = 'http://reporting-dev.bwaserver.com/api/reports/olap/?fn=';

// ==========================DEV VARIABLES ENDS ====================================================================================

export const IABCategories = [
  { value: "IAB1", text: "Arts & Entertainment" },
  { value: "IAB1-1", text: "Books & Literature" },
  { value: "IAB1-2", text: "Celebrity Fan/Gossip" },
  { value: "IAB1-3", text: "Fine Art" },
  { value: "IAB1-4", text: "Humor" },
  { value: "IAB1-5", text: "Movies" },
  { value: "IAB1-6", text: "Music" },
  { value: "IAB1-7", text: "Television" },
  { value: "IAB2", text: "Automotive" },
  { value: "IAB2-1", text: "Auto Parts" },
  { value: "IAB2-2", text: "Auto Repair " },
  { value: "IAB2-3", text: "Buying/Selling Cars" },
  { value: "IAB2-4", text: "Car Culture" },
  { value: "IAB2-5", text: "Certified Pre-Owned" },
  { value: "IAB2-6", text: "Convertible" },
  { value: "IAB2-7", text: "Coupe" },
  { value: "IAB2-8", text: "Crossover" },
  { value: "IAB2-9", text: "Diesel" },
  { value: "IAB2-10", text: "Electric Vehicle" },
  { value: "IAB2-11", text: "Hatchback" },
  { value: "IAB2-12", text: "Hybrid" },
  { value: "IAB2-13", text: "Luxury" },
  { value: "IAB2-14", text: "MiniVan" },
  { value: "IAB2-15", text: "Mororcycles" },
  { value: "IAB2-16", text: "Off-Road Vehicles" },
  { value: "IAB2-17", text: "Performance Vehicles" },
  { value: "IAB2-18", text: "Pickup" },
  { value: "IAB2-19", text: "Road-Side Assistance" },
  { value: "IAB2-20", text: "Sedan" },
  { value: "IAB2-21", text: "Trucks & Accessories" },
  { value: "IAB2-22", text: "Vintage Cars" },
  { value: "IAB2-23", text: "Wagon" },
  { value: "IAB3", text: "Business" },
  { value: "IAB3-1", text: "Advertising" },
  { value: "IAB3-2", text: "Agriculture" },
  { value: "IAB3-3", text: "Biotech/Biomedical" },
  { value: "IAB3-4", text: "Business Software" },
  { value: "IAB3-5", text: "Construction" },
  { value: "IAB3-6", text: "Forestry" },
  { value: "IAB3-7", text: "Government" },
  { value: "IAB3-8", text: "Green Solutions" },
  { value: "IAB3-9", text: "Human Resources" },
  { value: "IAB3-10", text: "Logistics" },
  { value: "IAB3-11", text: "Marketing" },
  { value: "IAB3-12", text: "Metals" },
  { value: "IAB4", text: "Careers" },
  { value: "IAB4-1", text: "Career Planning" },
  { value: "IAB4-2", text: "College" },
  { value: "IAB4-3", text: "Financial  Aid" },
  { value: "IAB4-4", text: "Job Fairs" },
  { value: "IAB4-5", text: "Job Search" },
  { value: "IAB4-6", text: "Resume Writing/Advice" },
  { value: "IAB4-7", text: "Nursing" },
  { value: "IAB4-8", text: "Scholarships" },
  { value: "IAB4-9", text: "Telecommuting" },
  { value: "IAB4-10", text: "U.S Military" },
  { value: "IAB4-11", text: "Career Advice" },
  { value: "IAB5", text: "Education" },
  { value: "IAB5-1", text: "7-12 Education" },
  { value: "IAB5-2", text: "Adult Education" },
  { value: "IAB5-3", text: "Art History" },
  { value: "IAB5-4", text: "Colledge Administration" },
  { value: "IAB5-5", text: "College Life" },
  { value: "IAB5-6", text: "Distance Learning" },
  { value: "IAB5-7", text: "English as a 2nd Language" },
  { value: "IAB5-8", text: "Language Learning" },
  { value: "IAB5-9", text: "Graduate School" },
  { value: "IAB5-10", text: "Homeschooling" },
  { value: "IAB5-11", text: "Homework/Study Tips" },
  { value: "IAB5-12", text: "K-6 Educators" },
  { value: "IAB5-13", text: "Private School" },
  { value: "IAB5-14", text: "Special Education" },
  { value: "IAB5-15", text: "Studying Business" },
  { value: "IAB6", text: "Family & Parenting" },
  { value: "IAB6-1", text: "Adoption" },
  { value: "IAB6-2", text: "Babies & Toddlers" },
  { value: "IAB6-3", text: "Daycare /Pre School" },
  { value: "IAB6-4", text: "Family Internet" },
  { value: "IAB6-5", text: "Parenting- K - 6 Kids" },
  { value: "IAB6-6", text: "Parenting teens" },
  { value: "IAB6-7", text: "Pregnancy" },
  { value: "IAB6-8", text: "Special Needs Kids" },
  { value: "IAB6-9", text: "Eldercare" },
  { value: "IAB7", text: "Health & Fitness" },
  { value: "IAB7-1", text: "Exercise" },
  { value: "IAB7-2", text: "A.D.D." },
  { value: "IAB7-3", text: "AIDS /HIV" },
  { value: "IAB7-4", text: "Allergies" },
  { value: "IAB7-5", text: "Alternative Medicine" },
  { value: "IAB7-6", text: "Arthritis" },
  { value: "IAB7-7", text: "Asthma" },
  { value: "IAB7-8", text: "Autism /PDD" },
  { value: "IAB7-9", text: "Bipolar Disorder" },
  { value: "IAB7-10", text: "Brain Tumor" },
  { value: "IAB7-11", text: "Cancer" },
  { value: "IAB7-12", text: "Cholesterol" },
  { value: "IAB7-13", text: "Chronic Fatigue Syndrome" },
  { value: "IAB7-14", text: "Chronic Pain" },
  { value: "IAB7-15", text: "Cold & Flu" },
  { value: "IAB7-16", text: "Deafness" },
  { value: "IAB7-17", text: "Dental Care" },
  { value: "IAB7-18", text: "Depression" },
  { value: "IAB7-19", text: "Dermatology" },
  { value: "IAB7-20", text: "Diabetes" },
  { value: "IAB7-21", text: "Epilepsy" },
  { value: "IAB7-22", text: "GERD /Acid Reflux" },
  { value: "IAB7-23", text: "Headaches /Migraines" },
  { value: "IAB7-24", text: "Heart Disease" },
  { value: "IAB7-25", text: "Herbs for Health" },
  { value: "IAB7-26", text: "Holistic Healing" },
  { value: "IAB7-27", text: "IBS /Crohn's Disease" },
  { value: "IAB7-28", text: "Incest /Abuse Support" },
  { value: "IAB7-29", text: "Incontinence" },
  { value: "IAB7-30", text: "Infertility" },
  { value: "IAB7-31", text: "Men's Health" },
  { value: "IAB7-32", text: "Nutrition" },
  { value: "IAB7-33", text: "Orthopedics" },
  { value: "IAB7-34", text: "Panic/Anxiety Disorders" },
  { value: "IAB7-35", text: "Pediatrics" },
  { value: "IAB7-36", text: "Physical Therapy" },
  { value: "IAB7-37", text: "Psychology /Psychiatry" },
  { value: "IAB7-38", text: "Senor Health" },
  { value: "IAB7-39", text: "Sexuality" },
  { value: "IAB7-40", text: "Sleep Disorders" },
  { value: "IAB7-41", text: "Smoking Cessation" },
  { value: "IAB7-42", text: "Substance Abuse" },
  { value: "IAB7-43", text: "Thyroid Disease" },
  { value: "IAB7-44", text: "Weight Loss" },
  { value: "IAB7-45", text: "Women's Health" },
  { value: "IAB8", text: "Food & Drink" },
  { value: "IAB8-1", text: "American Cuisine" },
  { value: "IAB8-2", text: "Barbecues & Grilling" },
  { value: "IAB8-3", text: "Cajun /Creole" },
  { value: "IAB8-4", text: "Chinese Cuisine" },
  { value: "IAB8-5", text: "Cocktails /Beer" },
  { value: "IAB8-6", text: "Coffee /Tea" },
  { value: "IAB8-7", text: "Cuisine -Specific" },
  { value: "IAB8-8", text: "Desserts & Baking" },
  { value: "IAB8-9", text: "Dining Out" },
  { value: "IAB8-10", text: "Food Allergies" },
  { value: "IAB8-11", text: "French Cuisine" },
  { value: "IAB8-12", text: "Health /Lowfat Cooking" },
  { value: "IAB8-13", text: "Italian Cuisine" },
  { value: "IAB8-14", text: "Japanese Cuisine" },
  { value: "IAB8-15", text: "Mexican Cuisine" },
  { value: "IAB8-16", text: "Vegan" },
  { value: "IAB8-17", text: "Vegetarian" },
  { value: "IAB8-18", text: "Wine" },
  { value: "IAB9", text: "Hobbies& Interests" },
  { value: "IAB9-1", text: "Art /Technology" },
  { value: "IAB9-2", text: "Arts & Crafts" },
  { value: "IAB9-3", text: "Beadwork" },
  { value: "IAB9-4", text: "Birdwatching" },
  { value: "IAB9-5", text: "Board Games / Puzzles" },
  { value: "IAB9-6", text: "Candle & Soap Making" },
  { value: "IAB9-7", text: "Card Games" },
  { value: "IAB9-8", text: "Chess" },
  { value: "IAB9-9", text: "Cigars" },
  { value: "IAB9-10", text: "Collecting" },
  { value: "IAB9-11", text: "Comic Books" },
  { value: "IAB9-12", text: "Drawing /Sketching" },
  { value: "IAB9-13", text: "Freelance Writing" },
  { value: "IAB9-14", text: "Genealogy" },
  { value: "IAB9-15", text: "Getting Published" },
  { value: "IAB9-16", text: "Guitar" },
  { value: "IAB9-17", text: "Home Recording" },
  { value: "IAB9-18", text: "Investors & Patents" },
  { value: "IAB9-19", text: "Jewelry Making" },
  { value: "IAB9-20", text: "Magic & Illusion" },
  { value: "IAB9-21", text: "Needlework" },
  { value: "IAB9-22", text: "Painting" },
  { value: "IAB9-23", text: "Photography" },
  { value: "IAB9-24", text: "Radio" },
  { value: "IAB9-25", text: "Roleplaying Games" },
  { value: "IAB9-26", text: "Sci-Fi & Fantasy" },
  { value: "IAB9-27", text: "Scrapbooking" },
  { value: "IAB9-28", text: "Screenwriting" },
  { value: "IAB9-29", text: "Stamps & Coins" },
  { value: "IAB9-30", text: "Video & Computer Games" },
  { value: "IAB9-31", text: "Woodworking" },
  { value: "IAB10", text: "Home & Garden" },
  { value: "IAB10-1", text: "Appliances" },
  { value: "IAB10-2", text: "Entertaining" },
  { value: "IAB10-3", text: "Environmental Safety" },
  { value: "IAB10-4", text: "Gardening" },
  { value: "IAB10-5", text: "Home Repair" },
  { value: "IAB10-6", text: "Home Theater" },
  { value: "IAB10-7", text: "Interior Decorating" },
  { value: "IAB10-8", text: "Landscaping" },
  { value: "IAB10-9", text: "Remodeling & Construction" },
  { value: "IAB11", text: "Law, Gov't & Politics" },
  { value: "IAB11-1", text: "Immigration" },
  { value: "IAB11-2", text: "Legal Issues" },
  { value: "IAB11-3", text: "U.S Government Resources" },
  { value: "IAB11-4", text: "Politics" },
  { value: "IAB11-5", text: "Commentary" },
  { value: "IAB12", text: "News" },
  { value: "IAB12-1", text: "International News" },
  { value: "IAB12-2", text: "National News" },
  { value: "IAB12-3", text: "Local News" },
  { value: "IAB13", text: "Finance Personal" },
  { value: "IAB13-1", text: "Beginning Investing" },
  { value: "IAB13-2", text: "Credit /Debt & Loans" },
  { value: "IAB13-3", text: "Financial News" },
  { value: "IAB13-4", text: "Financial Planning" },
  { value: "IAB13-5", text: "Hedge Fund" },
  { value: "IAB13-6", text: "Insurance" },
  { value: "IAB13-7", text: "Investing" },
  { value: "IAB13-8", text: "Mutual Funds" },
  { value: "IAB13-9", text: "Options" },
  { value: "IAB13-10", text: "Retirement Planning" },
  { value: "IAB13-11", text: "Stocks" },
  { value: "IAB13-12", text: "Tax Planning" },
  { value: "IAB14", text: "Society" },
  { value: "IAB14-1", text: "Dating" },
  { value: "IAB14-2", text: "Divorce Support" },
  { value: "IAB14-3", text: "Gay Life" },
  { value: "IAB14-4", text: "Marriage" },
  { value: "IAB14-5", text: "Senior Living" },
  { value: "IAB14-6", text: "Teens" },
  { value: "IAB14-7", text: "Weddings" },
  { value: "IAB14-8", text: "Ethnic Specific" },
  { value: "IAB15", text: "Science" },
  { value: "IAB15-1", text: "Astrology" },
  { value: "IAB15-2", text: "Biology" },
  { value: "IAB15-3", text: "Chemistry" },
  { value: "IAB15-4", text: "Geology" },
  { value: "IAB15-5", text: "Paranormal Phenomena" },
  { value: "IAB15-6", text: "Physics" },
  { value: "IAB15-7", text: "Space/Astronomy" },
  { value: "IAB15-8", text: "Geography" },
  { value: "IAB15-9", text: "Botany" },
  { value: "IAB15-10", text: "Weather" },
  { value: "IAB16", text: "Pets" },
  { value: "IAB16-1", text: "Aquariums" },
  { value: "IAB16-2", text: "Birds" },
  { value: "IAB16-3", text: "Cats" },
  { value: "IAB16-4", text: "Dogs" },
  { value: "IAB16-5", text: "Large Animals" },
  { value: "IAB16-6", text: "Reptiles" },
  { value: "IAB16-7", text: "Veterinary Medicine" },
  { value: "IAB17", text: "Sports" },
  { value: "IAB17-1", text: "AutoRacing" },
  { value: "IAB17-2", text: "Baseball" },
  { value: "IAB17-3", text: "Bicycling" },
  { value: "IAB17-4", text: "Bodybuilding" },
  { value: "IAB17-5", text: "Boxing" },
  { value: "IAB17-6", text: "Canoeing /Kayaking" },
  { value: "IAB17-7", text: "Cheerleading" },
  { value: "IAB17-8", text: "Climbing" },
  { value: "IAB17-9", text: "Cricket" },
  { value: "IAB17-10", text: "Figure Skating" },
  { value: "IAB17-11", text: "Fly Fishing" },
  { value: "IAB17-12", text: "Football" },
  { value: "IAB17-13", text: "Freshwater Fishing" },
  { value: "IAB17-14", text: "Game & Fish" },
  { value: "IAB17-15", text: "Golf" },
  { value: "IAB17-16", text: "Horse Racing" },
  { value: "IAB17-17", text: "Horses" },
  { value: "IAB17-18", text: "Hunting /Shooting" },
  { value: "IAB17-19", text: "Inline Skating" },
  { value: "IAB17-20", text: "Martial Arts" },
  { value: "IAB17-21", text: "Mountain Biking" },
  { value: "IAB17-22", text: "NASCAR Racing" },
  { value: "IAB17-23", text: "Olympics" },
  { value: "IAB17-24", text: "Paintball" },
  { value: "IAB17-25", text: "Power & Motorcycles" },
  { value: "IAB17-26", text: "Pro Basketball" },
  { value: "IAB17-27", text: "Pro Ice Hockey" },
  { value: "IAB17-28", text: "Rodeo" },
  { value: "IAB17-29", text: "Rugby" },
  { value: "IAB17-30", text: "Running /Jogging" },
  { value: "IAB17-31", text: "Sailing" },
  { value: "IAB17-32", text: "Saltwater Fishing" },
  { value: "IAB17-33", text: "Scuba Diving" },
  { value: "IAB17-34", text: "Skateboarding" },
  { value: "IAB17-35", text: "Skiing" },
  { value: "IAB17-36", text: "Snowboarding" },
  { value: "IAB17-37", text: "Surfing /Bodyboarding" },
  { value: "IAB17-38", text: "Swimming" },
  { value: "IAB17-39", text: "Table Tennis / Ping - Pong" },
  { value: "IAB17-40", text: "Tennis" },
  { value: "IAB17-41", text: "Volleyball" },
  { value: "IAB17-42", text: "Walking" },
  { value: "IAB17-43", text: "Waterski /Wakeboard" },
  { value: "IAB17-44", text: "World Soccer" },
  { value: "IAB18", text: "Style & Fashion" },
  { value: "IAB18-1", text: "Beauty" },
  { value: "IAB18-2", text: "Body Art" },
  { value: "IAB18-3", text: "Fashion" },
  { value: "IAB18-4", text: "Jewelry" },
  { value: "IAB18-5", text: "Clothing" },
  { value: "IAB18-6", text: "Accessories" },
  { value: "IAB19", text: "Technology& Computing" },
  { value: "IAB19-1", text: "3-D Graphics" },
  { value: "IAB19-2", text: "Animation" },
  { value: "IAB19-3", text: "Antivirus Software" },
  { value: "IAB19-4", text: "C/C++" },
  { value: "IAB19-5", text: "Cameras & Camcorders" },
  { value: "IAB19-6", text: "Cell Phones" },
  { value: "IAB19-7", text: "Computer Certification" },
  { value: "IAB19-8", text: "Computer Networking" },
  { value: "IAB19-9", text: "Computer Peripherals" },
  { value: "IAB19-10", text: "Computer Reviews" },
  { value: "IAB19-11", text: "Data Centers" },
  { value: "IAB19-12", text: "Databases" },
  { value: "IAB19-13", text: "Desktop Publishing" },
  { value: "IAB19-14", text: "Desktop Video" },
  { value: "IAB19-15", text: "Email" },
  { value: "IAB19-16", text: "Graphics Software" },
  { value: "IAB19-17", text: "Home Video / DVD" },
  { value: "IAB19-18", text: "Internet Technology" },
  { value: "IAB19-19", text: "Java" },
  { value: "IAB19-20", text: "JavaScript" },
  { value: "IAB19-21", text: "Mac Support" },
  { value: "IAB19-22", text: "MP3 /MIDI" },
  { value: "IAB19-23", text: "Net Conferencing" },
  { value: "IAB19-24", text: "Net for Beginners" },
  { value: "IAB19-25", text: "Network Security" },
  { value: "IAB19-26", text: "Palmtops /PDAs" },
  { value: "IAB19-27", text: "PC Support" },
  { value: "IAB19-28", text: "Portable" },
  { value: "IAB19-29", text: "Entertainment" },
  { value: "IAB19-30", text: "Shareware /Freeware" },
  { value: "IAB19-31", text: "Unix" },
  { value: "IAB19-32", text: "Visual Basic" },
  { value: "IAB19-33", text: "Web Clip Art" },
  { value: "IAB19-34", text: "Web Design / HTML" },
  { value: "IAB19-35", text: "Web Search" },
  { value: "IAB19-36", text: "Windows" },
  { value: "IAB20", text: "Travel" },
  { value: "IAB20-1", text: "Adventure Travel" },
  { value: "IAB20-2", text: "Africa" },
  { value: "IAB20-3", text: "Air Travel" },
  { value: "IAB20-4", text: "Australia & New Zealand" },
  { value: "IAB20-5", text: "Bed & Breakfasts" },
  { value: "IAB20-6", text: "Budget Travel" },
  { value: "IAB20-7", text: "Business Travel" },
  { value: "IAB20-8", text: "By US Locale" },
  { value: "IAB20-9", text: "Camping" },
  { value: "IAB20-10", text: "Canada" },
  { value: "IAB20-11", text: "Caribbean" },
  { value: "IAB20-12", text: "Cruises" },
  { value: "IAB20-13", text: "Eastern Europe" },
  { value: "IAB20-14", text: "Europe" },
  { value: "IAB20-15", text: "France" },
  { value: "IAB20-16", text: "Greece" },
  { value: "IAB20-17", text: "Honeymoons/Getaways" },
  { value: "IAB20-18", text: "Hotels" },
  { value: "IAB20-19", text: "Italy" },
  { value: "IAB20-20", text: "Japan" },
  { value: "IAB20-21", text: "Mexico & Central America" },
  { value: "IAB20-22", text: "National Parks" },
  { value: "IAB20-23", text: "South America" },
  { value: "IAB20-24", text: "Spas" },
  { value: "IAB20-25", text: "Theme Parks" },
  { value: "IAB20-26", text: "Traveling with Kids" },
  { value: "IAB20-27", text: "United  Kingdom" },
  { value: "IAB21", text: "Real Estate" },
  { value: "IAB21-1", text: "Apartments" },
  { value: "IAB21-2", text: "Architects" },
  { value: "IAB21-3", text: "Buying /Selling Homes" },
  { value: "IAB22", text: "Shopping" },
  { value: "IAB22-1", text: "Contests & Freebies" },
  { value: "IAB22-2", text: "Couponing" },
  { value: "IAB22-3", text: "Comparison" },
  { value: "IAB22-4", text: "Engines" },
  { value: "IAB23", text: "Religion& Spirituality" },
  { value: "IAB23-1", text: "Alternative Religions" },
  { value: "IAB23-2", text: "Atheism /Agnosticism" },
  { value: "IAB23-3", text: "Buddhism" },
  { value: "IAB23-4", text: "Catholicism" },
  { value: "IAB23-5", text: "Christianity" },
  { value: "IAB23-6", text: "Hinduism" },
  { value: "IAB23-7", text: "Islam" },
  { value: "IAB23-8", text: "Judaism" },
  { value: "IAB23-9", text: "Latter-Day Saints" },
  { value: "IAB23-10", text: "Pagan /Wiccan" },
  { value: "IAB24", text: "Uncategorized" },
  { value: "IAB25", text: "Non-Standard Content" },
  { value: "IAB25-1", text: "Unmoderated UGC" },
  { value: "IAB25-2", text: "Extreme  Graphic / Explicit Violence" },
  { value: "IAB25-3", text: "Pornography" },
  { value: "IAB25-4", text: "Profane Content" },
  { value: "IAB25-5", text: "Hate  Content" },
  { value: "IAB25-6", text: "Under  Construction" },
  { value: "IAB25-7", text: "Incentivized" },
  { value: "IAB26", text: "Illegal Content" },
  { value: "IAB26-1", text: "Illegal Content" },
  { value: "IAB26-2", text: "Warez" },
  { value: "IAB26-3", text: "Spyware/Malware" },
  { value: "IAB26-4", text: "Copyright  Infringement" }
];

export const TAXONOMY = [
  {
    main: { name: "Arts & Entertainment", code: "IAB1" },
    subs: [
      { name: "Books & Literature", code: "IAB1-1" },
      { name: "Celebrity Fan/Gossip", code: "IAB1-2" },
      { name: "Fine Art", code: "IAB1-3" },
      { name: "Humor", code: "IAB1-4" },
      { name: "Movies", code: "IAB1-5" },
      { name: "Music", code: "IAB1-6" },
      { name: "Television", code: "IAB1-7" }
    ],
    active: false
  },
  {
    main: { name: "Automotive", code: "IAB2" },
    subs: [
      { name: "Auto Parts", code: "IAB2-1" },
      { name: "Auto Repair", code: "IAB2-2" },
      { name: "Buying/Selling Cars", code: "IAB2-3" },
      { name: "Car Culture", code: "IAB2-4" },
      { name: "Certified Pre-Owned", code: "IAB2-5" },
      { name: "Convertible", code: "IAB2-6" },
      { name: "Coupe", code: "IAB2-7" },
      { name: "Crossover", code: "IAB2-8" },
      { name: "Diesel", code: "IAB2-9" },
      { name: "Electric Vehicle", code: "IAB2-10" },
      { name: "Hatchback", code: "IAB2-11" },
      { name: "Hybrid", code: "IAB2-12" },
      { name: "Luxury", code: "IAB2-13" },
      { name: "MiniVan", code: "IAB2-14" },
      { name: "Motorcycles", code: "IAB2-15" },
      { name: "Off-Road Vehicles", code: "IAB2-16" },
      { name: "Performance Vehicles", code: "IAB2-17" },
      { name: "Pickup", code: "IAB2-18" },
      { name: "Road-Side Assistance", code: "IAB2-19" },
      { name: "Sedan", code: "IAB2-20" },
      { name: "Trucks & Accessories", code: "IAB2-21" },
      { name: "Vintage Cars", code: "IAB2-22" },
      { name: "Wagon", code: "IAB2-23" }
    ],
    active: false
  },
  {
    main: { name: "Business", code: "IAB3" },
    subs: [
      { name: "Advertising", code: "IAB3-1" },
      { name: "Agriculture", code: "IAB3-2" },
      { name: "Biotech/Biomedical", code: "IAB3-3" },
      { name: "Business Software", code: "IAB3-4" },
      { name: "Construction", code: "IAB3-5" },
      { name: "Forestry", code: "IAB3-6" },
      { name: "Government", code: "IAB3-7" },
      { name: "Green Solutions", code: "IAB3-8" },
      { name: "Human Resources", code: "IAB3-9" },
      { name: "Logistics", code: "IAB3-10" },
      { name: "Marketing", code: "IAB3-11" },
      { name: "Metals", code: "IAB3-12" }
    ],
    active: false
  },
  {
    main: { name: "Careers", code: "IAB4" },
    subs: [
      { name: "Career Planning", code: "IAB4-1" },
      { name: "College", code: "IAB4-2" },
      { name: "Financial Aid", code: "IAB4-3" },
      { name: "Job Fairs", code: "IAB4-4" },
      { name: "Job Search", code: "IAB4-5" },
      { name: "Resume Writing/Advice", code: "IAB4-6" },
      { name: "Nursing", code: "IAB4-7" },
      { name: "Scholarships", code: "IAB4-8" },
      { name: "Telecommuting", code: "IAB4-9" },
      { name: "U.S. Military", code: "IAB4-10" },
      { name: "Career Advice", code: "IAB4-11" }
    ],
    active: false
  },
  {
    main: { name: "Education", code: "IAB5" },
    subs: [
      { name: "7-12 Education", code: "IAB5-1" },
      { name: "Adult Education", code: "IAB5-2" },
      { name: "Art History", code: "IAB5-3" },
      { name: "College Administration", code: "IAB5-4" },
      { name: "College Life", code: "IAB5-5" },
      { name: "Distance Learning", code: "IAB5-6" },
      { name: "English as a 2nd Language", code: "IAB5-7" },
      { name: "Language Learning", code: "IAB5-8" },
      { name: "Graduate School", code: "IAB5-9" },
      { name: "Homeschooling", code: "IAB5-10" },
      { name: "Homework/Study Tips", code: "IAB5-11" },
      { name: "K-6 Educators", code: "IAB5-12" },
      { name: "Private School", code: "IAB5-13" },
      { name: "Special Education", code: "IAB5-14" },
      { name: "Studying Business", code: "IAB5-15" }
    ],
    active: false
  },
  {
    main: { name: "Family & Parenting", code: "IAB6" },
    subs: [
      { name: "Adoption", code: "IAB6-1" },
      { name: "Babies & Toddlers", code: "IAB6-2" },
      { name: "Daycare/Pre School", code: "IAB6-3" },
      { name: "Family Internet", code: "IAB6-4" },
      { name: "Parenting - K-6 Kids", code: "IAB6-5" },
      { name: "Parenting teens", code: "IAB6-6" },
      { name: "Pregnancy", code: "IAB6-7" },
      { name: "Special Needs Kids", code: "IAB6-8" },
      { name: "Eldercare", code: "IAB6-9" }
    ]
  },
  {
    main: { name: "Health & Fitness", code: "IAB7" },
    subs: [
      { name: "Exercise", code: "IAB7-1" },
      { name: "A.D.D", code: "IAB7-2" },
      { name: "AIDS/HIV", code: "IAB7-3" },
      { name: "Allergies", code: "IAB7-4" },
      { name: "Alternative Medicine", code: "IAB7-5" },
      { name: "Arthritis", code: "IAB7-6" },
      { name: "Asthma", code: "IAB7-7" },
      { name: "Autism/PDD", code: "IAB7-8" },
      { name: "Bipolar Disorder", code: "IAB7-9" },
      { name: "Brain Tumor", code: "IAB7-10" },
      { name: "Cancer", code: "IAB7-11" },
      { name: "Cholesterol", code: "IAB7-12" },
      { name: "Chronic Fatigue Syndrome", code: "IAB7-13" },
      { name: "Chronic Pain", code: "IAB7-14" },
      { name: "Cold & Flu", code: "IAB7-15" },
      { name: "Deafness", code: "IAB7-16" },
      { name: "Dental Care", code: "IAB7-17" },
      { name: "Depression", code: "IAB7-18" },
      { name: "Dermatology", code: "IAB7-19" },
      { name: "Diabetes", code: "IAB7-20" },
      { name: "Epilepsy", code: "IAB7-21" },
      { name: "GERD/Acid Reflux", code: "IAB7-22" },
      { name: "Headaches/Migranes", code: "IAB7-23" },
      { name: "Heart Disease", code: "IAB7-24" },
      { name: "Herbs for Health", code: "IAB7-25" },
      { name: "Holistic Healing", code: "IAB7-26" },
      { name: "IBS/Crohn's Disease", code: "IAB7-27" },
      { name: "Incest/Abuse Support", code: "IAB7-28" },
      { name: "Incontinence", code: "IAB7-29" },
      { name: "Infertility", code: "IAB7-30" },
      { name: "Men's Health", code: "IAB7-31" },
      { name: "Nutrition", code: "IAB7-32" },
      { name: "Orthopedics", code: "IAB7-33" },
      { name: "Panic/Anxiety Disorders", code: "IAB7-34" },
      { name: "Pediatrics", code: "IAB7-35" },
      { name: "Physcial Therapy", code: "IAB7-36" },
      { name: "Psychology/Psychiatry", code: "IAB7-37" },
      { name: "Senior Health", code: "IAB7-38" },
      { name: "Sexuality", code: "IAB7-39" },
      { name: "Sleep Disorders", code: "IAB7-40" },
      { name: "Smoking Cessation", code: "IAB7-41" },
      { name: "Substance Abuse", code: "IAB7-42" },
      { name: "Thyroid Disease", code: "IAB7-43" },
      { name: "Weight Loss", code: "IAB7-44" },
      { name: "Women's Health", code: "IAB7-45" }
    ],
    active: false
  },
  {
    main: { name: "Food & Drink", code: "IAB8" },
    subs: [
      { name: "American Cuisine", code: "IAB8-1" },
      { name: "Barbecues & Grilling", code: "IAB8-2" },
      { name: "Cajun/Creole", code: "IAB8-3" },
      { name: "Chinese Cuisine", code: "IAB8-4" },
      { name: "Cocktails/Beer", code: "IAB8-5" },
      { name: "Coffee/Tea", code: "IAB8-6" },
      { name: "Cuisine-Specific", code: "IAB8-7" },
      { name: "Desserts & Baking", code: "IAB8-8" },
      { name: "Dining Out", code: "IAB8-9" },
      { name: "Food Allergies", code: "IAB8-10" },
      { name: "French Cuisine", code: "IAB8-11" },
      { name: "Health/Lowfat Cooking", code: "IAB8-12" },
      { name: "Italian Cuisine", code: "IAB8-13" },
      { name: "Japanese Cuisine", code: "IAB8-14" },
      { name: "Mexican Cuisine", code: "IAB8-15" },
      { name: "Vegan", code: "IAB8-16" },
      { name: "Vegetarian", code: "IAB8-17" },
      { name: "Wine", code: "IAB8-18" }
    ],
    active: false
  },
  {
    main: { name: "Hobbies & Interests", code: "IAB9" },
    subs: [
      { name: "Art/technology", code: "IAB9-1" },
      { name: "Arts & Crafts", code: "IAB9-2" },
      { name: "Beadwork", code: "IAB9-3" },
      { name: "Birdwatching", code: "IAB9-4" },
      { name: "Board Games/Puzzles", code: "IAB9-5" },
      { name: "Candle & Soap Making", code: "IAB9-6" },
      { name: "Card Games", code: "IAB9-7" },
      { name: "Chess", code: "IAB9-8" },
      { name: "Cigars", code: "IAB9-9" },
      { name: "Collecting", code: "IAB9-10" },
      { name: "Comic Books", code: "IAB9-11" },
      { name: "Drawing/Sketching", code: "IAB9-12" },
      { name: "Freelance Writing", code: "IAB9-13" },
      { name: "Genealogy", code: "IAB9-14" },
      { name: "Getting Published", code: "IAB9-15" },
      { name: "Guitar", code: "IAB9-16" },
      { name: "Home Recording", code: "IAB9-17" },
      { name: "Investors & Patents", code: "IAB9-18" },
      { name: "Jewelry Making", code: "IAB9-19" },
      { name: "Magic & Illusion", code: "IAB9-20" },
      { name: "Needlework", code: "IAB9-21" },
      { name: "Painting", code: "IAB9-22" },
      { name: "Photography", code: "IAB9-23" },
      { name: "Radio", code: "IAB9-24" },
      { name: "Roleplaying Games", code: "IAB9-25" },
      { name: "Sci-Fi & Fantasy", code: "IAB9-26" },
      { name: "Scrapbooking", code: "IAB9-27" },
      { name: "Screenwriting", code: "IAB9-28" },
      { name: "Stamps & Coins", code: "IAB9-29" },
      { name: "Video & Computer Games", code: "IAB9-30" },
      { name: "Woodworking", code: "IAB9-31" }
    ],
    active: false
  },
  {
    main: { name: "Home & Garden", code: "IAB10" },
    subs: [
      { name: "Appliances", code: "IAB10-1" },
      { name: "Entertaining", code: "IAB10-2" },
      { name: "Environmental Safety", code: "IAB10-3" },
      { name: "Gardening", code: "IAB10-4" },
      { name: "Home Repair", code: "IAB10-5" },
      { name: "Home Theater", code: "IAB10-6" },
      { name: "Interior Decorating", code: "IAB10-7" },
      { name: "Landscaping", code: "IAB10-8" },
      { name: "Remodeling & Construction", code: "IAB10-9" }
    ],
    active: false
  },
  {
    main: { name: "Law, Gov't & Politics", code: "IAB11" },
    subs: [
      { name: "Immigration", code: "IAB11-1" },
      { name: "Legal Issues", code: "IAB11-2" },
      { name: "U.S. Government Resources", code: "IAB11-3" },
      { name: "Politics", code: "IAB11-4" },
      { name: "Commentary", code: "IAB11-5" }
    ],
    active: false
  },
  {
    main: { name: "News", code: "IAB12" },
    subs: [
      { name: "International News", code: "IAB12-1" },
      { name: "National News", code: "IAB12-2" },
      { name: "Local News", code: "IAB12-3" },
    ],
    active: false
  },
  {
    main: { name: "Personal Finance", code: "IAB13" },
    subs: [
      { name: "Beginning Investing", code: "IAB13-1" },
      { name: "Credit/Debt & Laons", code: "IAB13-2" },
      { name: "Financial News", code: "IAB13-3" },
      { name: "Financial Planning", code: "IAB13-4" },
      { name: "Hedge Fund", code: "IAB13-5" },
      { name: "Insurance", code: "IAB13-6" },
      { name: "Investing", code: "IAB13-7" },
      { name: "Mutual Funds", code: "IAB13-8" },
      { name: "Options", code: "IAB13-9" },
      { name: "Retirement Planning", code: "IAB13-10" },
      { name: "Stocks", code: "IAB13-11" },
      { name: "Tax Planning", code: "IAB13-12" }
    ],
    active: false
  },
  {
    main: { name: "Society", code: "IAB14" },
    subs: [
      { name: "Dating", code: "IAB14-1" },
      { name: "Divorce Support", code: "IAB14-2" },
      { name: "Gay Life", code: "IAB14-3" },
      { name: "Marriage", code: "IAB14-4" },
      { name: "Senior Living", code: "IAB14-5" },
      { name: "Teens", code: "IAB14-6" },
      { name: "Weddings", code: "IAB14-7" },
      { name: "Ethnic Specific", code: "IAB14-8" }
    ],
    active: false
  },
  {
    main: { name: "Science", code: "IAB15" },
    subs: [
      { name: "Astrology", code: "IAB15-1" },
      { name: "Biology", code: "IAB15-2" },
      { name: "Chemistry", code: "IAB15-3" },
      { name: "Geology", code: "IAB15-4" },
      { name: "Paranormal Phenomena", code: "IAB15-5" },
      { name: "Physics", code: "IAB15-6" },
      { name: "Space/Astronomy", code: "IAB15-7" },
      { name: "Geography", code: "IAB15-8" },
      { name: "Botany", code: "IAB15-9" },
      { name: "Weather", code: "IAB15-10" }
    ],
    active: false
  },
  {
    main: { name: "Pets", code: "IAB16" },
    subs: [
      { name: "Aquariums", code: "IAB16-1" },
      { name: "Birds", code: "IAB16-2" },
      { name: "Cats", code: "IAB16-3" },
      { name: "Dogs", code: "IAB16-4" },
      { name: "Large Animals", code: "IAB16-5" },
      { name: "Reptiles", code: "IAB16-6" },
      { name: "Veterinary Medicine", code: "IAB16-7" }
    ],
    active: false
  },
  {
    main: { name: "Sports", code: "IAB17" },
    subs: [
      { name: "Auto Racing", code: "IAB17-1" },
      { name: "Baseball", code: "IAB17-2" },
      { name: "Bicycling", code: "IAB17-3" },
      { name: "Bodybuilding", code: "IAB17-4" },
      { name: "Boxing", code: "IAB17-5" },
      { name: "Canoeing/Kayaking", code: "IAB17-6" },
      { name: "Cheerleading", code: "IAB17-7" },
      { name: "Climbing", code: "IAB17-8" },
      { name: "Cricket", code: "IAB17-9" },
      { name: "Figure Skating", code: "IAB17-10" },
      { name: "Fly Fishing", code: "IAB17-11" },
      { name: "Football", code: "IAB17-12" },
      { name: "Freshwater Fishing", code: "IAB17-13" },
      { name: "Game & Fish", code: "IAB17-14" },
      { name: "Golf", code: "IAB17-15" },
      { name: "Horse Racing", code: "IAB17-16" },
      { name: "Horses", code: "IAB17-17" },
      { name: "Hunting/Shooting", code: "IAB17-18" },
      { name: "Inline Skating", code: "IAB17-19" },
      { name: "Martial Arts", code: "IAB17-20" },
      { name: "Mountain Biking", code: "IAB17-21" },
      { name: "NASCAR Racing", code: "IAB17-22" },
      { name: "Olympics", code: "IAB17-23" },
      { name: "Paintball", code: "IAB17-24" },
      { name: "Power & Motorcycles", code: "IAB17-25" },
      { name: "Pro Basketball", code: "IAB17-26" },
      { name: "Pro Ice Hockey", code: "IAB17-27" },
      { name: "Rodeo", code: "IAB17-28" },
      { name: "Rugby", code: "IAB17-29" },
      { name: "Running/Jogging", code: "IAB17-30" },
      { name: "Sailing", code: "IAB17-31" },
      { name: "Saltwater Fishing", code: "IAB17-32" },
      { name: "Scuba Diving", code: "IAB17-33" },
      { name: "Skateboarding", code: "IAB17-34" },
      { name: "Skiing", code: "IAB17-35" },
      { name: "Snowboarding", code: "IAB17-36" },
      { name: "Surfing/Bodyboarding", code: "IAB17-37" },
      { name: "Swimming", code: "IAB17-38" },
      { name: "Table Tennis/Ping-Pong", code: "IAB17-39" },
      { name: "Tennis", code: "IAB17-40" },
      { name: "Volleyball", code: "IAB17-41" },
      { name: "Walking", code: "IAB17-42" },
      { name: "Waterski/Wakeboard", code: "IAB17-43" },
      { name: "World Soccer", code: "IAB17-44" }
    ],
    active: false
  },
  {
    main: { name: "Style & Fashion", code: "IAB18" },
    subs: [
      { name: "Beauty", code: "IAB18-1" },
      { name: "Body Art", code: "IAB18-2" },
      { name: "Fashion", code: "IAB18-3" },
      { name: "Jewelry", code: "IAB18-4" },
      { name: "Clothing", code: "IAB18-5" },
      { name: "Accessories", code: "IAB18-6" }
    ],
    active: false
  },
  {
    main: { name: "Technology & Computing", code: "IAB19" },
    subs: [
      { name: "3-D Graphics", code: "IAB19-1" },
      { name: "Animation", code: "IAB19-2" },
      { name: "Antivirus Software", code: "IAB19-3" },
      { name: "C/C++", code: "IAB19-4" },
      { name: "Cameras & Camcorders", code: "IAB19-5" },
      { name: "Cell Phones", code: "IAB19-6" },
      { name: "Computer Certification", code: "IAB19-7" },
      { name: "Computer Networking", code: "IAB19-8" },
      { name: "Computer Peripherals", code: "IAB19-9" },
      { name: "Computer Reviews", code: "IAB19-10" },
      { name: "Data Centers", code: "IAB19-11" },
      { name: "Databases", code: "IAB19-12" },
      { name: "Desktop Publishing", code: "IAB19-13" },
      { name: "Desktop Video", code: "IAB19-14" },
      { name: "Email", code: "IAB19-15" },
      { name: "Graphics Software", code: "IAB19-16" },
      { name: "Home Video/DVD", code: "IAB19-17" },
      { name: "Internet Technology", code: "IAB19-18" },
      { name: "Java", code: "IAB19-19" },
      { name: "JavaScript", code: "IAB19-20" },
      { name: "Mac Support", code: "IAB19-21" },
      { name: "MP3/MIDI", code: "IAB19-22" },
      { name: "Net Conferencing", code: "IAB19-23" },
      { name: "Net for Beginners", code: "IAB19-24" },
      { name: "Network Security", code: "IAB19-25" },
      { name: "Palmtops/PDAs", code: "IAB19-26" },
      { name: "PC Support", code: "IAB19-27" },
      { name: "Portable", code: "IAB19-28" },
      { name: "Entertainment", code: "IAB19-29" },
      { name: "Shareware/Freeware", code: "IAB19-30" },
      { name: "Unix", code: "IAB19-31" },
      { name: "Visual Basic", code: "IAB19-32" },
      { name: "Web Clip Art", code: "IAB19-33" },
      { name: "Web Design/HTML", code: "IAB19-34" },
      { name: "Web Search", code: "IAB19-35" },
      { name: "Windows", code: "IAB19-36" }
    ],
    active: false
  },
  {
    main: { name: "Travel", code: "IAB20" },
    subs: [
      { name: "Adventure Travel", code: "IAB20-1" },
      { name: "Africa", code: "IAB20-2" },
      { name: "Air Travel", code: "IAB20-3" },
      { name: "Australia & New Zealand", code: "IAB20-4" },
      { name: "Bed & Breakfasts", code: "IAB20-5" },
      { name: "Budget Travel", code: "IAB20-6" },
      { name: "Business Travel", code: "IAB20-7" },
      { name: "By US Locale", code: "IAB20-8" },
      { name: "Camping", code: "IAB20-9" },
      { name: "Canada", code: "IAB20-10" },
      { name: "Caribbean", code: "IAB20-11" },
      { name: "Cruises", code: "IAB20-12" },
      { name: "Eastern Europe", code: "IAB20-13" },
      { name: "Europe", code: "IAB20-14" },
      { name: "France", code: "IAB20-15" },
      { name: "Greece", code: "IAB20-16" },
      { name: "Honeymoons/Getaways", code: "IAB20-17" },
      { name: "Hotels", code: "IAB20-18" },
      { name: "Italy", code: "IAB20-19" },
      { name: "Japan", code: "IAB20-20" },
      { name: "Mexico & Central America", code: "IAB20-21" },
      { name: "National Parks", code: "IAB20-22" },
      { name: "South America", code: "IAB20-23" },
      { name: "Spas", code: "IAB20-24" },
      { name: "Theme Parks", code: "IAB20-25" },
      { name: "Traveling with Kids", code: "IAB20-26" },
      { name: "United Kingdom", code: "IAB20-27" }
    ],
    active: false
  },
  {
    main: { name: "Real Estate", code: "IAB21" },
    subs: [
      { name: "Apartments", code: "IAB21-1" },
      { name: "Architects", code: "IAB21-2" },
      { name: "Buying/Selling Homes", code: "IAB21-3" }
    ],
    active: false
  },
  {
    main: { name: "Shopping", code: "IAB22" },
    subs: [
      { name: "Contests & Freebies", code: "IAB22-1" },
      { name: "Couponing", code: "IAB22-2" },
      { name: "Comparison", code: "IAB22-3" },
      { name: "Engines", code: "IAB22-4" }
    ],
    active: false
  },
  {
    main: { name: "Religion & Spirituality", code: "IAB23" },
    subs: [
      { name: "Alternative Religions", code: "IAB23-1" },
      { name: "Atheism/Agnosticism", code: "IAB23-2" },
      { name: "Buddhism", code: "IAB23-3" },
      { name: "Catholicism", code: "IAB23-4" },
      { name: "Christianity", code: "IAB23-5" },
      { name: "Hinduism", code: "IAB23-6" },
      { name: "Islam", code: "IAB23-7" },
      { name: "Judaism", code: "IAB23-8" },
      { name: "Latter-Day Saints", code: "IAB23-9" },
      { name: "Pagan/Wiccan", code: "IAB23-10" }
    ],
    active: false
  },
  {
    main: { name: "Uncategorized", code: "IAB24" },
    subs: [],
    active: false
  }
];
export const MAX_UPLOAD_SIZE_DISPLAY = 2097152;
export const MAX_UPLOAD_SIZE_VIDEO = 103809024;
export const REFRESH_RATE = 10000;
export const VERSION = 'Dev build: 2018-07-20';
