// MENU TYPES

export const CHANGE_MENU_STATE = 'CHANGE_MENU_STATE';
export const MENU_RESET_ACTIVE = 'MENU_RESET_ACTIVE';

// ACCOUNTS TYPES
export const LIST_ACCOUNTS = 'LIST_ACCOUNTS';
export const READ_ACCOUNT = 'READ_ACCOUNT';
export const RESET_ACCOUNTS_REDUCER = 'RESET_ACCOUNTS_REDUCER';
export const CHANGE_ACCOUNTS = 'CHANGE_ACCOUNTS';
export const DISPLAY_ACCOUNT = 'DISPLAY_ACCOUNT';
export const RESET_ACCOUNT_ERRORS = 'RESET_ACCOUNT_ERRORS';
export const ACCOUNTS_LIST_ERROR = 'ACCOUNTS_LIST_ERROR';
export const ACCOUNT_READ_ERROR = 'ACCOUNT_READ_ERROR';
export const READ_ACTIVE_ACCOUNT = 'READ_ACTIVE_ACCOUNT';
export const LIST_MASTER_ACCOUNTS = 'LIST_MASTER_ACCOUNTS';

// USERS TYPES

export const LIST_USERS = 'LIST_USERS';
export const UPDATE_USER = 'UPDATE_USER';
export const CREATE_USER = 'CREATE_USER';
export const READ_USER = 'READ_USER';
export const READ_DISPLAY_USER = 'READ_DISPLAY_USER';
export const READ_ACTIVE_USER = 'READ_ACTIVE_USER';
export const RESET_USER_REDUCER = 'RESET_USER_REDUCER';
export const RESET_USERS_REDUCER = 'RESET_USERS_REDUCER';
export const SET_USER_TIMEZONE = 'SET_USER_TIMEZONE';
export const CHANGE_USERS = 'CHANGE_USERS';
export const DISPLAY_USER = 'DISPLAY_USER';
export const RESET_USER_ERRORS = 'RESET_USER_ERRORS';
export const USER_CREATE_ERROR = 'USER_CREATE_ERROR';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const USERS_LIST_ERROR = 'USERS_LIST_ERROR';
export const USER_READ_ERROR = 'USER_READ_ERROR';
export const USER_READ_DISPLAY_ERROR = 'USER_READ_DISPLAY_ERROR';
export const ACTIVE_USER_READ_ERROR = 'ACTIVE_USER_READ_ERROR';
export const USER_ACTION = 'USER_ACTION';

// ADVERTISERS TYPES
export const LIST_ADVERTISERS = 'LIST_ADVERTISERS';
export const READ_ADVERTISER = 'READ_ADVERTISER';
export const RESET_ADVERTISERS_REDUCER = 'RESET_ADVERTISERS_REDUCER';
export const CHANGE_ADVERTISERS = 'CHANGE_ADVERTISERS';
export const DISPLAY_ADVERTISER = 'DISPLAY_ADVERTISER';
export const READ_ACTIVE_ADVERTISER = 'READ_ACTIVE_ADVERTISER';
export const RESET_ADVERTISER_ERRORS = 'RESET_ADVERTISER_ERRORS';
export const ADVERTISERS_LIST_ERROR = 'ADVERTISERS_LIST_ERROR';
export const ADVERTISER_READ_ERROR = 'ADVERTISER_READ_ERROR';

// CAMPAIGNS TYPES

export const LIST_CAMPAIGN_ADVERTISERS = 'LIST_CAMPAIGN_ADVERTISERS';
export const LIST_CAMPAIGNS = 'LIST_CAMPAIGNS';
export const READ_CAMPAIGN = 'READ_CAMPAIGN';
export const RESET_CAMPAIGNS_REDUCER = 'RESET_CAMPAIGNS_REDUCER';
export const CHANGE_CAMPAIGNS = 'CHANGE_CAMPAIGNS';
export const DISPLAY_CAMPAIGN = 'DISPLAY_CAMPAIGN';
export const CAMPAIGN_READ_ERROR = 'CAMPAIGN_READ_ERROR';
export const RESET_CAMPAIGN_ERRORS = 'RESET_CAMPAIGN_ERRORS';
export const CAMPAIGNS_LIST_ERROR = 'CAMPAIGNS_LIST_ERROR';
export const CAMPAIGN_PIXEL_TAG = 'CAMPAIGN_PIXEL_TAG'

// PUBLISHERS TYPES

export const LIST_PUBLISHERS = 'LIST_PUBLISHERS';
export const READ_PUBLISHER = 'READ_PUBLISHER';
export const RESET_PUBLISHERS_REDUCER = 'RESET_PUBLISHERS_REDUCER';
export const DISPLAY_PUBLISHER = 'DISPLAY_PUBLISHER';
export const RESET_PUBLISHER_ERRORS = 'RESET_PUBLISHER_ERRORS';
export const PUBLISHERS_LIST_ERROR = 'PUBLISHERS_LIST_ERROR';
export const PUBLISHER_READ_ERROR = 'PUBLISHER_READ_ERROR';
export const CHANGE_PUBLISHERS = 'CHANGE_PUBLISHERS';


// INTEGRATIONS
export const LIST_INTEGRATIONS_DROPDOWN = 'LIST_INTEGRATIONS_DROPDOWN';
export const LIST_INTEGRATIONS_DROPDOWN_ERROR = 'LIST_INTEGRATIONS_DROPDOWN_ERROR';
export const LIST_INTEGRATIONS = 'LIST_INTEGRATIONS';
export const INTEGRATIONS_LIST_ERROR = 'INTEGRATIONS_LIST_ERROR';
export const RESET_INTEGRATIONS_REDUCER = 'RESET_INTEGRATIONS_REDUCER';
export const CHANGE_INTEGRATIONS = 'CHANGE_INTEGRATIONS';
export const DISPLAY_INTEGRATION = 'DISPLAY_INTEGRATION';
export const RESET_INTEGRATION_ERRORS = 'RESET_INTEGRATION_ERRORS';
export const INTEGRATION_READ_ERROR = 'INTEGRATION_READ_ERROR';
export const READ_INTEGRATION = 'READ_INTEGRATION';
export const READ_ACTIVE_INTEGRATION = 'READ_ACTIVE_INTEGRATION';
export const CHECK_IFLIGHT ='CHECK_IFLIGHT';
// BEACONS TYPES

export const LIST_BEACONS = 'LIST_BEACONS';
export const CREATE_BEACON = 'CREATE_BEACON';
export const LIST_DISABLED_BEACONS = 'LIST_DISABLED_BEACONS';
export const READ_BEACON = 'READ_BEACON';
export const RESET_BEACONS_REDUCER = 'RESET_BEACONS_REDUCER';
export const RESET_BEACON_REDUCER = 'RESET_BEACON_REDUCER';
export const BEACON_CREATE_ERROR = 'BEACON_CREATE_ERROR';
export const RESET_BEACON_ERRORS = 'RESET_BEACONS_ERRORS';
export const BEACONS_LIST_ERROR = 'BECAONS_LIST_ERROR';
export const BEACON_READ_DISPLAY_ERROR = 'BEACON_READ_DISPLAY_ERROR';
export const BEACON_ACTION = 'BEACON_ACTION';

// PLACEMENTS TYPES
export const LIST_PLACEMENTS = 'LIST_PLACEMENTS';
export const LIST_PLACEMENT_PUBLISHERS = 'LIST_PLACEMENT_PUBLISHERS';
export const READ_PLACEMENT = 'READ_PLACEMENT';
export const RESET_PLACEMENTS_REDUCER = 'RESET_PLACEMENTS_REDUCER';
export const RESET_PLACEMENT_REDUCER = 'RESET_PLACEMENT_REDUCER';
export const READ_ACTIVE_PUBLISHER = 'READ_ACTIVE_PUBLISHER';
export const CHANGE_PLACEMENTS = 'CHANGE_PLACEMENTS';
export const DISPLAY_PLACEMENT = 'DISPLAY_PLACEMENT';
export const DISPLAY_TAG = 'DISPLAY_TAG';
export const PLAYER_DISPLAY_TAG = 'export const';
export const CHANGE_PLACEMENT = 'CHANGE_PLACEMENT';
export const PLACEMENT_ERROR = 'PLACEMENT_ERROR';
export const PLACEMENT_SUCCESS = 'PLACEMENT_SUCCESS';
export const PLACEMENT_FAIL = 'PLACEMENT_FAIL';
export const PLACEMENTS_LIST_ERROR = 'PLACEMENTS_LIST_ERROR';
export const RESET_PLACEMENT_ERRORS = 'RESET_PLACEMENT_ERRORS';
export const LIST_DEMAND = 'LIST_DEMAND';
export const PLACEMENT_FLIGHTS = 'PLACEMENT_FLIGHTS';
export const DEMAND_FAIL = 'DEMAND_FAIL';
export const PLACEMENT_GEO_SEARCH = 'PLACEMENT_GEO_SEARCH';

export const READ_OPPORTUNITY_COUNT = 'READ_OPPORTUNITY_COUNT';
export const OPPORTUNITY_COUNT_ERROR = 'OPPORTUNITY_COUNT_ERROR';

// FLIGHT TYPES
export const LIST_FLIGHT_CAMPAIGNS = 'LIST_FLIGHT_CAMPAIGNS';
export const UPLOAD_FLIGHT_DISPLAY_CREATIVE = 'UPLOAD_FLIGHT_DISPLAY_CREATIVE';
export const UPLOAD_FLIGHT_VIDEO_CREATIVE = 'UPLOAD_FLIGHT_VIDEO_CREATIVE';
export const UPLOAD_FLIGHT_COMPANION_CREATIVE = 'UPLOAD_FLIGHT_COMPANION_CREATIVE';
export const READ_FLIGHT = 'READ_FLIGHT';
export const LIST_FLIGHTS = 'LIST_FLIGHTS';
export const RESET_FLIGHTS_REDUCER = 'RESET_FLIGHTS_REDUCER';
export const RESET_FLIGHT_REDUCER = 'RESET_FLIGHT_REDUCER';
export const READ_ACTIVE_CAMPAIGN = 'READ_ACTIVE_CAMPAIGN';
export const CHANGE_FLIGHTS = 'CHANGE_FLIGHTS';
export const CHANGE_FLIGHT = 'CHANGE_FLIGHT';
export const RESET_DISPLAY_ERRORS = 'RESET_DISPLAY_ERRORS';
export const RESET_DISPLAY_CREATIVE = 'RESET_DISPLAY_CREATIVE';
export const RESET_VIDEO_ERRORS = 'RESET_VIDEO_ERRORS';
export const RESET_VIDEO_CREATIVE = 'RESET_VIDEO_CREATIVE';
export const LIST_FLIGHT_OPTIONS = 'LIST_FLIGHT_OPTIONS';
export const DISPLAY_FLIGHT = 'DISPLAY_FLIGHT';
export const FLIGHTS_LIST_ERROR = 'FLIGHTS_LIST_ERROR';
export const RESET_FLIGHT_ERRORS = 'RESET_FLIGHT_ERRORS';
export const FLIGHT_SUCCESS = 'FLIGHT_SUCCESS';
export const FLIGHT_ERROR = 'FLIGHT_ERROR';
export const FLIGHT_FAIL = 'FLIGHT_FAIL';
export const FLIGHT_GEO_SEARCH = 'FLIGHT_GEO_SEARCH';

export const FLIGHTS_PLACEMENT = 'FLIGHTS_PLACEMENT';
export const SUPPLY_FAIL = 'SUPPLY_FAIL';
export const LIST_SUPPLY = 'LIST_SUPPLY';

// ANALYTICS TYPES

export const CHANGE_ANALYTICS_STATE = 'CHANGE_ANALYTICS_STATE';
export const OLAP_VALIDATION = 'OLAP_VALIDATION';
export const RUN_REPORT = 'RUN_REPORT';
export const OLAP_FILTER = 'OLAP_FILTER';
export const RESET_ANALYTICS_ERRORS = 'RESET_ANALYTICS_ERRORS';
export const SET_ANALYTICS_SORTING = 'SET_ANALYTICS_SORTING';
export const RUN_REPORT_CSV = 'RUN_REPORT_CSV';
export const RUN_REPORT_ERR = 'RUN_REPORT_ERR';

// REJECTIONS
export const CHANGE_REJECTIONS_STATE ='CHANGE_REJECTIONS_STATE'
export const OLAP_REJECTIONS_VALIDATION ='OLAP_REJECTIONS_VALIDATION'
export const OLAP_REJECTIONS_FILTER ='OLAP_REJECTIONS_FILTER'
export const RESET_REJECTIONS_ERRORS ='RESET_REJECTIONS_ERRORS'
export const RUN_REJECTIONS_REPORT ='RUN_REJECTIONS_REPORT'
export const SET_REJECTIONS_SORTING ='SET_REJECTIONS_SORTING'
export const RUN_REJECTIONS_REPORT_CSV ='RUN_REJECTIONS_REPORT_CSV'
export const RUN_REJECTIONS_REPORT_ERROR ='RUN_REJECTIONS_REPORT_ERROR'
// REPORTING TYPES

export const FETCH_AUTOCOMPLETE = 'FETCH_AUTOCOMPLETE';
export const RUN_PUB_REPORT = 'RUN_PUB_REPORT';
export const RESET_REPORTING_REDUCER = 'RESET_REPORTING_REDUCER';
export const PUB_REPORT_ERROR = 'PUB_REPORT_ERROR';
export const FETCH_ALL_PID = 'FETCH_ALL_PID';
export const FETCH_ALL_PID_ERR = 'FETCH_ALL_PID_ERR';


// DOMAIN LISTS TYPES

export const LIST_DOMAIN_LISTS = 'LIST_DOMAIN_LISTS';
export const LIST_DOMAIN_LISTS_ERROR = 'LIST_DOMAIN_LISTS_ERROR';
export const RESET_DOMAIN_LISTS_REDUCER = 'RESET_DOMAIN_LISTS_REDUCER';
export const DOMAIN_LISTS_CHANGE = 'DOMAIN_LISTS_CHANGE';
export const DOMAIN_LIST_CHANGE = 'DOMAIN_LIST_CHANGE';
export const DOMAIN_LIST_UPLOAD_SUCCESS = 'DOMAIN_LIST_UPLOAD_SUCCESS';
export const DOMAIN_LIST_UPLOAD_FAIL = 'DOMAIN_LIST_UPLOAD_FAIL';
export const DOMAIN_LIST_CREATE_SUCCESS = 'DOMAIN_LIST_CREATE_SUCCESS';
export const DOMAIN_LIST_CREATE_FAIL = 'DOMAIN_LIST_CREATE_FAIL';
export const RESET_DOMAIN_LIST_ERRORS = 'RESET_DOMAIN_LIST_ERRORS';
export const RESET_DOMAIN_LIST_REDUCER = 'RESET_DOMAIN_LIST_REDUCER';
export const DISPLAY_DOMAIN_LIST = 'DISPLAY_DOMAIN_LIST';
export const READ_DOMAIN_LIST = 'READ_DOMAIN_LIST';
export const DOMAIN_LIST_EDIT_FAIL = 'DOMAIN_LIST_EDIT_FAIL';
export const DOMAIN_LIST_UPDATE_SUCCESS = 'DOMAIN_LIST_UPDATE_SUCCESS';
export const DOMAIN_LIST_UPDATE_FAIL = 'DOMAIN_LIST_UPDATE_FAIL';
export const LIST_FLIGHT_DOMAIN_LISTS = 'LIST_FLIGHT_DOMAIN_LISTS';
export const LIST_PLACEMENT_DOMAIN_LISTS = 'LIST_PLACEMENT_DOMAIN_LISTS';
export const LIST_DOMAIN_TYPE = 'LIST_DOMAIN_TYPE';

// MODALS TYPES

export const MODAL_STATE_CHANGE = 'MODAL_STATE_CHANGE';
export const MODAL_ERROR = 'MODAL_ERROR';
export const MODAL_SUCCESS = 'MODAL_SUCCESS';
export const CLEAR_MODAL_ERRORS = 'CLEAR_MODAL_ERRORS';
export const RESET_MODAL_REDUCER = 'RESET_MODAL_REDUCER';
export const PIXEL_TAG ='PIXEL_TAG';

// AUTH TYPES

export const AUTH_CHANGE = 'AUTH_CHANGE';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const PASSWORD_RESET = 'PASSWORD_RESET';
export const RESET_AUTH_REDUCER = 'RESET_AUTH_REDUCER';
export const ACCOUNT_REQUEST_SUCCESS = 'ACCOUNT_REQUEST_SUCCESS';
export const ACCOUNT_REQUEST_ERROR = 'ACCOUNT_REQUEST_ERROR';

// DASHBOARD TYPES

export const CHANGE_DASHBOARD_STATE = 'CHANGE_DASHBOARD_STATE';
export const DASHBOARD_TABLE = 'DASHBOARD_TABLE';
export const DASHBOARD_KPI = 'DASHBOARD_KPI';
export const DASHBOARD_SUMMARY = 'DASHBOARD_SUMMARY';
export const DASHBOARD_PERFORMANCE = 'DASHBOARD_PERFORMANCE';
export const DASHBOARD_FINANCIALS = 'DASHBOARD_FINANCIALS';
export const DASHBOARD_DOMAINS = 'DASHBOARD_DOMAINS';
export const DASHBOARD_REACH = 'DASHBOARD_REACH';
export const DASHBOARD_TRAFFIC = 'DASHBOARD_TRAFFIC';
export const DASHBOARD_TOP_ADVERTISER ='DASHBOARD_TOP_ADVERTISER';
export const DASHBOARD_TABLE_TOP_PUBLISHER ='DASHBOARD_TABLE_TOP_PUBLISHER';