// Accounts actions
exports.LIST_ACCOUNTS = 'LIST_ACCOUNTS';
exports.READ_ACCOUNT = 'READ_ACCOUNT';
exports.CREATE_ACCOUNT = 'CREATE_ACCOUNT';
exports.DELETE_ACCOUNT = 'DELETE_ACCOUNT';
exports.UPDATE_ACCOUNT = 'UPDATE_ACCOUNT';
exports.LIST_PENDING_ACCOUNTS = 'LIST_PENDING_ACCOUNTS';
exports.LIST_DISABLED_ACCOUNTS = 'LIST_DISABLED_ACCOUNTS';
exports.ACTIVATE_ACCOUNT = 'ACTIVATE_ACCOUNT';
exports.DEACTIVATE_ACCOUNT = 'DEACTIVATE_ACCOUNT';
exports.LIST_MASTER_ACCOUNTS = 'LIST_MASTER_ACCOUNTS';

// Users actions
exports.SET_SCOPE = 'SET_SCOPE';
exports.READ_USER = 'READ_USER';
exports.LIST_USERS = 'LIST_USERS';
exports.CREATE_USER = 'CREATE_USER';
exports.UPDATE_USER = 'UPDATE_USERS';
exports.DELETE_USER = 'DELETE_USER';
exports.LIST_DISABLED_USERS = 'LIST_DISABLED_USERS';
exports.ACTIVATE_USER = 'ACTIVATE_USER';
exports.DEACTIVATE_USER = 'DEACTIVATE_USER';

// Advertisers actions
exports.CREATE_ADVERTISER = 'CREATE_ADVERTISER';
exports.LIST_ADVERTISERS = 'LIST_ADVERTISERS';
exports.READ_ADVERTISER = 'READ_ADVERTISER';
exports.DELETE_ADVERTISER = 'DELETE_ADVERTISER';
exports.UPDATE_ADVERTISER = 'UPDATE_ADVERTISER';
exports.LIST_DISABLED_ADVERTISERS = 'LIST_DISABLED_ADVERTISERS';

// Campaigns actions
exports.CREATE_CAMPAIGN = 'CREATE_CAMPAIGN';
exports.DELETE_CAMPAIGN = 'DELETE_CAMPAIGN';
exports.LIST_CAMPAIGNS = 'LIST_CAMPAIGNS';
exports.READ_CAMPAIGN = 'READ_CAMPAIGN';
exports.UPDATE_CAMPAIGN = 'UPDATE_CAMPAIGN';
exports.PAUSE_CAMPAIGN = 'PAUSE_CAMPAIGN';
exports.RESUME_CAMPAIGN = 'RESUME_CAMPAIGN';
exports.LIST_DISABLED_CAMPAIGNS = 'LIST_DISABLED_CAMPAIGNS';
exports.ACTIVATE_CAMPAIGN = 'ACTIVATE_CAMPAIGN';
exports.DEACTIVATE_CAMPAIGN = 'DEACTIVATE_CAMPAIGN';

// Publishers actions
exports.CREATE_PUBLISHER = 'CREATE_PUBLISHER';
exports.LIST_PUBLISHERS = 'LIST_PUBLISHERS';
exports.READ_PUBLISHER = 'READ_PUBLISHER';
exports.DELETE_PUBLISHER = 'DELETE_PUBLISHER';
exports.UPDATE_PUBLISHER = 'UPDATE_PUBLISHER';
exports.LIST_DISABLED_PUBLISHERS = 'LIST_DISABLED_PUBLISHERS';

// Integration actions
exports.CREATE_INTEGRATION = 'CREATE_INTEGRATION';
exports.LIST_INTEGRATIONS = 'LIST_INTEGRATIONS';
exports.READ_INTEGRATION = 'READ_INTEGRATION';
exports.DELETE_INTEGRATION = 'DELETE_INTEGRATION';
exports.UPDATE_INTEGRATION = 'UPDATE_INTEGRATION';
exports.LIST_DISABLED_INTEGRATIONS = 'LIST_DISABLED_INTEGRATIONS';

// Placements actions
exports.CREATE_PLACEMENT = 'CREATE_PLACEMENT';
exports.DELETE_PLACEMENT = 'DELETE_PLACEMENT';
exports.LIST_PLACEMENTS = 'LIST_PLACEMENTS';
exports.READ_PLACEMENT = 'READ_PLACEMENT';
exports.CLONE_PLACEMENT = 'CLONE_PLACEMENT';
exports.UPDATE_PLACEMENT = 'UPDATE_PLACEMENT';
exports.LIST_DISABLED_PLACEMENTS = 'LIST_DISABLED_PLACEMENTS';
exports.ACTIVATE_PLACEMENT = 'ACTIVATE_PLACEMENT';
exports.DEACTIVATE_PLACEMENT = 'DEACTIVATE_PLACEMENT';

// Flights actions
exports.CREATE_FLIGHT = 'CREATE_FLIGHT';
exports.DELETE_FLIGHT = 'DELETE_FLIGHT';
exports.LIST_FLIGHTS = 'LIST_FLIGHTS';
exports.READ_FLIGHT = 'READ_FLIGHT';
exports.UPDATE_FLIGHT = 'UPDATE_FLIGHT';
exports.CLONE_FLIGHT = 'CLONE_FLIGHT';
exports.ACTIVATE_FLIGHT = 'ACTIVATE_FLIGHT';
exports.DEACTIVATE_FLIGHT = 'DEACTIVATE_FLIGHT';
exports.LIST_DISABLED_FLIGHTS = 'LIST_DISABLED_FLIGHTS';

// Domain list actions
exports.LIST_DOMAIN_LISTS = 'LIST_DOMAIN_LISTS';
exports.LIST_DOMAIN_TYPE = 'LIST_DOMAIN_TYPE';
exports.UPLOAD_LISTS = 'UPLOAD_LISTS';
exports.CREATE_LIST = 'CREATE_LIST';
exports.READ_LIST = 'READ_LIST';
exports.UPDATE_LIST = 'UPDATE_LIST';
exports.DELETE_LIST = 'DELETE_LIST';